//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentTask2V3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerContainer : DbContext
    {
        public CustomerContainer()
            : base("name=CustomerContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }

        public System.Data.Entity.DbSet<AssessmentTask2V3.Models.CustomerForm.CustomerFormModel> CustomerFormModels { get; set; }

        public System.Data.Entity.DbSet<AssessmentTask2V3.Models.CustomerForm.LoginFormModel> LoginFormModels { get; set; }
    }
}
